import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "react-hot-toast";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className="min-h-screen bg-background antialiased">
        <TRPCReactProvider>
          <Toaster
            toastOptions={{
              className: "",
              style: {
                background: "#27272A",
                color: "#fff",
              },
            }}
          />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
